server:
  port: 8081
  tomcat:
    max-connections: 200      # ?? ?? ?? ?

filepath: C:/uploadFiles

# ?? ??? ?? ??
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # ??? ? ? ?? ? ?? ??
      max-request-size: 100MB  # ??? ??? ? ??
  web:
    resources:
      static-locations: file:///C:/uploadFiles/  # ?? ??? ??
      cache-period: 3600                        # ? ????? ?? ??(?, 1??)